from typing import Any
from fastapi import APIRouter, HTTPException, Depends
from sqlmodel import Session

from app.api.deps import CurrentUser, SessionDep
from app.core.config import settings
from app.models import (
    GuestCreate, 
    GuestResponse, 
    AddEmailRequest, 
    SendReportRequest, 
    Message,
    GuestReportPublic
)
from app.guest_service import (
    create_guest_user,
    add_email_to_guest,
    send_report_to_guest,
    get_guest_reports,
    is_guest_session_valid
)

router = APIRouter()


@router.post("/create", response_model=GuestResponse)
def create_guest(
    guest_data: GuestCreate,
    session: SessionDep
) -> Any:
    """
    Create a new guest user with or without email.
    
    - **email**: Optional email address for the guest
    
    Returns guest access token and session information.
    """
    if not settings.GUEST_ACCESS_ENABLED:
        raise HTTPException(
            status_code=403,
            detail="Guest access is currently disabled"
        )
    
    try:
        guest_user, token = create_guest_user(guest_data.email)
        
        return GuestResponse(
            access_token=token,
            token_type="bearer",
            guest_session_id=guest_user.guest_session_id,
            has_email=bool(guest_data.email)
        )
        
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to create guest user: {str(e)}"
        )


@router.post("/add-email", response_model=Message)
def add_guest_email(
    email_data: AddEmailRequest,
    current_user: CurrentUser
) -> Any:
    """
    Add email address to an existing anonymous guest user.
    
    Requires authentication as a guest user.
    """
    if not current_user.is_guest:
        raise HTTPException(
            status_code=403,
            detail="This endpoint is only available for guest users"
        )
    
    if current_user.guest_email:
        raise HTTPException(
            status_code=400,
            detail="Guest user already has an email address"
        )
    
    success = add_email_to_guest(current_user.id, email_data.email)
    
    if not success:
        raise HTTPException(
            status_code=500,
            detail="Failed to add email to guest account"
        )
    
    return Message(message="Email address added successfully")


@router.post("/send-report", response_model=Message)
async def send_guest_report(
    report_request: SendReportRequest,
    current_user: CurrentUser
) -> Any:
    """
    Send a report to the guest user's email address.
    
    Requires authentication as a guest user with an email address.
    """
    if not current_user.is_guest:
        raise HTTPException(
            status_code=403,
            detail="This endpoint is only available for guest users"
        )
    
    if not current_user.guest_email:
        raise HTTPException(
            status_code=400,
            detail="Guest user must have an email address to receive reports"
        )
    
    # Validate session is still active
    if not is_guest_session_valid(current_user.id):
        raise HTTPException(
            status_code=401,
            detail="Guest session has expired"
        )
    
    try:
        success = await send_report_to_guest(
            current_user.id,
            report_request.report_data,
            report_request.report_type
        )
        
        if not success:
            raise HTTPException(
                status_code=500,
                detail="Failed to send report"
            )
        
        return Message(message="Report sent successfully to your email")
        
    except ValueError as e:
        # Handle report limit exceeded
        raise HTTPException(
            status_code=429,
            detail=str(e)
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to send report: {str(e)}"
        )


@router.get("/reports", response_model=list[GuestReportPublic])
def get_guest_user_reports(
    current_user: CurrentUser
) -> Any:
    """
    Get all reports generated by the current guest user.
    
    Requires authentication as a guest user.
    """
    if not current_user.is_guest:
        raise HTTPException(
            status_code=403,
            detail="This endpoint is only available for guest users"
        )
    
    reports = get_guest_reports(current_user.id)
    
    return [
        GuestReportPublic(
            id=report.id,
            report_type=report.report_type,
            generated_at=report.generated_at,
            email_sent=report.email_sent,
            email_sent_at=report.email_sent_at
        )
        for report in reports
    ]


@router.get("/session/status", response_model=dict[str, Any])
def check_guest_session(
    current_user: CurrentUser
) -> Any:
    """
    Check the status of the current guest session.
    
    Returns session information including expiration time.
    """
    if not current_user.is_guest:
        raise HTTPException(
            status_code=403,
            detail="This endpoint is only available for guest users"
        )
    
    is_valid = is_guest_session_valid(current_user.id)
    
    return {
        "session_id": current_user.guest_session_id,
        "guest_type": current_user.guest_type,
        "has_email": bool(current_user.guest_email),
        "expires_at": current_user.expires_at.isoformat() if current_user.expires_at else None,
        "is_valid": is_valid,
        "reports_sent": len(get_guest_reports(current_user.id)),
        "max_reports": settings.GUEST_MAX_REPORTS
    }


@router.delete("/session", response_model=Message)
def delete_guest_session(
    current_user: CurrentUser,
    session: SessionDep
) -> Any:
    """
    Manually delete the current guest session and all associated data.
    
    This will immediately invalidate the session.
    """
    if not current_user.is_guest:
        raise HTTPException(
            status_code=403,
            detail="This endpoint is only available for guest users"
        )
    
    try:
        # Delete the guest user (this should cascade to reports)
        session.delete(current_user)
        session.commit()
        
        return Message(message="Guest session deleted successfully")
        
    except Exception as e:
        session.rollback()
        raise HTTPException(
            status_code=500,
            detail=f"Failed to delete guest session: {str(e)}"
        )