"""initializ params for cultivar_soybean4

Revision ID: 07e4c0048fac
Revises: 0afc7fb24b57
Create Date: 2026-01-16 20:09:19.157252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07e4c0048fac'
down_revision = '0afc7fb24b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    #op.alter_column("cultivar_soybean", "hybridname", server_default=sa.text('93B15'))
    op.alter_column("cultivar_soybean", "matGrp", server_default=sa.text("5.0"))
    op.alter_column("cultivar_soybean", "seedLb", server_default=sa.text("2800.0"))
    op.alter_column("cultivar_soybean", "fill", server_default=sa.text("4.0"))
    op.alter_column("cultivar_soybean", "v1", server_default=sa.text("0.00957"))
    op.alter_column("cultivar_soybean", "v2", server_default=sa.text("14.6"))
    op.alter_column("cultivar_soybean", "v3", server_default=sa.text("1.0"))
    op.alter_column("cultivar_soybean", "r1", server_default=sa.text("0.028"))
    op.alter_column("cultivar_soybean", "r2", server_default=sa.text("0.00619"))
    op.alter_column("cultivar_soybean", "r3", server_default=sa.text("-0.0907"))
    op.alter_column("cultivar_soybean", "r4", server_default=sa.text("0.161"))
    op.alter_column("cultivar_soybean", "r5", server_default=sa.text("0.522"))
    op.alter_column("cultivar_soybean", "r6", server_default=sa.text("120.1"))
    op.alter_column("cultivar_soybean", "r7", server_default=sa.text("0.0062"))
    op.alter_column("cultivar_soybean", "r8", server_default=sa.text("250.0"))
    op.alter_column("cultivar_soybean", "r9", server_default=sa.text("200.0"))
    op.alter_column("cultivar_soybean", "r10", server_default=sa.text("0.5"))
    op.alter_column("cultivar_soybean", "r11", server_default=sa.text("0.0024"))
    op.alter_column("cultivar_soybean", "r12", server_default=sa.text("3.8"))
    op.alter_column("cultivar_soybean", "g1", server_default=sa.text("0.0024"))
    op.alter_column("cultivar_soybean", "g2", server_default=sa.text("0.5"))
    op.alter_column("cultivar_soybean", "g3", server_default=sa.text("1.8"))
    op.alter_column("cultivar_soybean", "g4", server_default=sa.text("0.8"))
    op.alter_column("cultivar_soybean", "g5", server_default=sa.text("0.684"))
    op.alter_column("cultivar_soybean", "g6", server_default=sa.text("1.684"))
    op.alter_column("cultivar_soybean", "g7", server_default=sa.text("0.5"))
    op.alter_column("cultivar_soybean", "g8", server_default=sa.text("2.5"))
    op.alter_column("cultivar_soybean", "g9", server_default=sa.text("3.2"))
    op.alter_column("cultivar_soybean", "RRRM", server_default=sa.text("166.7"))
    op.alter_column("cultivar_soybean", "RRRY", server_default=sa.text("31.3"))
    op.alter_column("cultivar_soybean", "RVRL", server_default=sa.text("0.73"))
    op.alter_column("cultivar_soybean", "ALPM", server_default=sa.text("0.55"))
    op.alter_column("cultivar_soybean", "ALPY", server_default=sa.text("0.04"))
    op.alter_column("cultivar_soybean", "RTWL", server_default=sa.text("0.000106"))
    op.alter_column("cultivar_soybean", "RTMinWTperArea", server_default=sa.text("0.0002"))
    op.alter_column("cultivar_soybean", "EPSI", server_default=sa.text("1"))
    op.alter_column("cultivar_soybean", "IUPW", server_default=sa.text("1"))
    op.alter_column("cultivar_soybean", "CourMax", server_default=sa.text("1"))
    op.alter_column("cultivar_soybean", "Diffx", server_default=sa.text("2.4"))
    op.alter_column("cultivar_soybean", "Diffz", server_default=sa.text("2.9"))
    op.alter_column("cultivar_soybean", "VelZ", server_default=sa.text("0"))
    op.alter_column("cultivar_soybean", "lsink", server_default=sa.text("1"))
    op.alter_column("cultivar_soybean", "Rroot", server_default=sa.text("0.017"))
    op.alter_column("cultivar_soybean", "Constl_M", server_default=sa.text("35.0"))
    op.alter_column("cultivar_soybean", "ConstK_M", server_default=sa.text("0.5"))
    op.alter_column("cultivar_soybean", "Cmin0_M", server_default=sa.text("0.01"))
    op.alter_column("cultivar_soybean", "ConstI_Y", server_default=sa.text("17.2"))
    op.alter_column("cultivar_soybean", "ConstK_Y", server_default=sa.text("0.75"))
    op.alter_column("cultivar_soybean", "Cmin0_Y", server_default=sa.text("0.03"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
