"""remove autincrementing from some g0 tables

Revision ID: 093e25298b13
Revises: 19e0a50f5c7d
Create Date: 2026-01-16 13:56:42.851066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '093e25298b13'
down_revision = '19e0a50f5c7d'
branch_labels = None
depends_on = None
tables2 =[
     "g01_soybean", "g05_soybean", "g07_cotton",  "g07_fallow",
       "g07_soybean","g03_fallow","g03_soybean","g04_cotton",
       "g04_soybean", "g05_fallow", "nitrogen_soybean",
       "plantStress_fallow", "plantStress_soybean",
       "plantStress_cotton", "plantStress_maize", 
       "plantStress_potato"
]
tables1=[
       "plantStress_fallow", "plantStress_soybean",
        "plantStress_maize",  "plantStress_potato",
        "nitrogen_potato","nitrogen_soybean"

]


def upgrade():
     for table in tables2:
            col=f"{table}_id"
            print(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" DROP DEFAULT;')
            op.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{col}" DROP DEFAULT;') 
            
            seq=f"{table}_{table}_id_seq"
            op.execute(f"DROP SEQUENCE IF EXISTS {seq};")
     
    #op.execute('ALTER TABLE "plantStress_fallow" ALTER COLUMN id ADD GENERATED BY DEFAULT AS #IDENTITY;')       
     for  table in tables1:
            ky=f"{table}_pkey"
            op.drop_constraint(ky, table, type_='primary')




def downgrade():
    pass
