"""initializ params for cultivar_soybean3

Revision ID: 0afc7fb24b57
Revises: 178185664fb8
Create Date: 2026-01-16 20:06:04.769822

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0afc7fb24b57'
down_revision = '178185664fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
