"""add LM-Min to maize

Revision ID: 12d91303177a
Revises: 91b0b9683b97
Create Date: 2026-01-12 03:04:47.609749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '12d91303177a'
down_revision = '91b0b9683b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultivar_maize', sa.Column('LM_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cultivar_maize', 'LM_min')
    # ### end Alembic commands ###
