"""creating site table

Revision ID: 17989c70d578
Revises: ded1e55af0ec
Create Date: 2024-05-03 17:21:29.229788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17989c70d578'
down_revision = 'ded1e55af0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site",
        sa.Column("sitename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rlat", sa.Float, nullable=False),
        sa.Column("rlon", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.droptable("site")
    # ### end Alembic commands ###