"""Add biologydefault table

Revision ID: 2d4e05df73d8
Revises: 8cd1d5ae2367
Create Date: 2026-01-10 21:21:27.755642

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d4e05df73d8'
down_revision = '8cd1d5ae2367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biologydefault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dthH', sa.Float(), nullable=True),
    sa.Column('dthL', sa.Float(), nullable=True),
    sa.Column('es', sa.Float(), nullable=True),
    sa.Column('Th_m', sa.Float(), nullable=True),
    sa.Column('tb', sa.Float(), nullable=True),
    sa.Column('QT', sa.Float(), nullable=True),
    sa.Column('dThD', sa.Float(), nullable=True),
    sa.Column('Th_d', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('pastruns', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('pastruns_owner_id_fkey'), 'pastruns', type_='foreignkey')
    op.drop_column('pastruns', 'odate')
    op.alter_column('soil_long', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               autoincrement=True)
    op.execute("CREATE TYPE guesttype AS ENUM ('ANONYMOUS', 'EMAIL')")
    op.execute("UPDATE \"user\" SET guest_type = 'ANONYMOUS' WHERE guest_type = 'anonymous'")
    op.execute("UPDATE \"user\" SET guest_type = 'EMAIL' WHERE guest_type = 'email'")
 
    op.execute("""
              ALTER TABLE "user" 
              ALTER COLUMN guest_type TYPE guesttype 
              USING guest_type::guesttype
     """)
    op.alter_column('user', 'guest_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ANONYMOUS', 'EMAIL', name='guesttype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'guest_type',
               existing_type=sa.Enum('ANONYMOUS', 'EMAIL', name='guesttype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('soil_long', 'id',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('pastruns', sa.Column('odate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pastruns_owner_id_fkey'), 'pastruns', 'pastruns', ['owner_id'], ['id'])
    op.alter_column('pastruns', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('biologydefault')
    # ### end Alembic commands ###
