"""adding additional soybean cultivar fields

Revision ID: 2d65dd617fdc
Revises: 093e25298b13
Create Date: 2026-01-16 17:40:13.174157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d65dd617fdc'
down_revision = '093e25298b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultivar_soybean', sa.Column('RRRM', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('RRRY', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('RVRL', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('ALPM', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('ALPY', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('RTWL', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('RTMinWTperArea', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('EPSI', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('IUPW', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('CourMax', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Diffx', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Diffz', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('VelZ', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('lsink', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Rroot', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Constl_M', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('ConstK_M', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Cmin0_M', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('ConstI_Y', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('ConstK_Y', sa.Float(), nullable=True))
    op.add_column('cultivar_soybean', sa.Column('Cmin0_Y', sa.Float(), nullable=True))
    op.alter_column('cultivar_soybean', 'matGrp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'seedLb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'fill',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'v1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'v2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'v3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r7',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r11',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'r12',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g7',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_soybean', 'g9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.alter_column('cultivar_soybean', 'g9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g7',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'g1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r12',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r11',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r7',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'r1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'v3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'v2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'v1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'fill',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'seedLb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_soybean', 'matGrp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('cultivar_soybean', 'Cmin0_Y')
    op.drop_column('cultivar_soybean', 'ConstK_Y')
    op.drop_column('cultivar_soybean', 'ConstI_Y')
    op.drop_column('cultivar_soybean', 'Cmin0_M')
    op.drop_column('cultivar_soybean', 'ConstK_M')
    op.drop_column('cultivar_soybean', 'Constl_M')
    op.drop_column('cultivar_soybean', 'Rroot')
    op.drop_column('cultivar_soybean', 'lsink')
    op.drop_column('cultivar_soybean', 'VelZ')
    op.drop_column('cultivar_soybean', 'Diffz')
    op.drop_column('cultivar_soybean', 'Diffx')
    op.drop_column('cultivar_soybean', 'CourMax')
    op.drop_column('cultivar_soybean', 'IUPW')
    op.drop_column('cultivar_soybean', 'EPSI')
    op.drop_column('cultivar_soybean', 'RTMinWTperArea')
    op.drop_column('cultivar_soybean', 'RTWL')
    op.drop_column('cultivar_soybean', 'ALPY')
    op.drop_column('cultivar_soybean', 'ALPM')
    op.drop_column('cultivar_soybean', 'RVRL')
    op.drop_column('cultivar_soybean', 'RRRY')
    op.drop_column('cultivar_soybean', 'RRRM')
    # ### end Alembic commands ###
