"""creating grid ratio table

Revision ID: 2eb08d169d1d
Revises: fcf2cc8d1ae7
Create Date: 2024-05-22 13:49:18.749519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2eb08d169d1d'
down_revision = 'fcf2cc8d1ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gridratio',
    sa.Column("gridratio_id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("gridratio_id"),
    sa.Column("SR1", sa.Float(), nullable=False),
    sa.Column("SR2", sa.Float(), nullable=False),
    sa.Column("IR1", sa.Float(), nullable=False),
    sa.Column("IR2", sa.Float(), nullable=False),
    sa.Column("PlantingDepth", sa.Float(), nullable=False),
    sa.Column("XLimitRoot", sa.Float(), nullable=False),
    sa.Column("BottomBC", sa.Integer()),
    sa.Column("GasBCTop", sa.Integer(),server_default= "-4"),
    sa.Column("GasBCBottom", sa.Integer(), server_default= "1"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.deletetable("gridratio")
    # ### end Alembic commands ###
