"""adding_biologydefault_table

Revision ID: 381387ae589a
Revises: 17989c70d578
Create Date: 2024-05-20 12:34:05.432484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '381387ae589a'
down_revision = '17989c70d578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biologydefault",
        sa.Column("dthH", sa.Float(), nullable=False),
        sa.Column("dthL", sa.Float(), nullable=False),
        sa.Column("es", sa.Float(), nullable=False),
        sa.Column("Th_m", sa.Float(), nullable=False),
        sa.Column("tb", sa.Float(), nullable=False),
        sa.Column("QT", sa.Float(), nullable=False),
        sa.Column("dThD", sa.Float(), nullable=False),
        sa.Column("Th_d", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.droptable("biologydefault")
    # ### end Alembic commands ###