"""Add column N2O to soil_long model

Revision ID: 421753f0620f
Revises: a2b59d5fd251
Create Date: 2025-03-18 13:17:03.011321

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '421753f0620f'
down_revision = 'a2b59d5fd251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_long', sa.Column('N2O', sa.REAL(), nullable=False, server_default= "0.0"))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soil_long', 'N2O')
    # ### end Alembic commands ###