"""adding additional soybean cultivar fields with data

Revision ID: 45e4540e9f66
Revises: 2d65dd617fdc
Create Date: 2026-01-16 18:26:31.201037

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45e4540e9f66'
down_revision = '2d65dd617fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
