"""Create fertilizationOp table

Revision ID: 49947b2471ec
Revises: 3703c0de746a
Create Date: 2024-08-14 14:37:49.720789

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49947b2471ec'
down_revision = '3703c0de746a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizationOp',
    sa.Column('fertilizationClass', sa.String(), nullable=False),
    sa.Column('depth', sa.String(), nullable=False),
    sa.Column('opID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('opID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertilizationOp')
    # ### end Alembic commands ###
