"""add default as identity for soybean plant stress

Revision ID: 4f4e6af708a8
Revises: 54d9d6130f24
Create Date: 2026-01-18 23:17:01.838943

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4f4e6af708a8'
down_revision = '54d9d6130f24'
branch_labels = None
depends_on = None

def upgrade():
   op.execute(f'ALTER TABLE "plantStress_soybean" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;')  


def downgrade():
   op.execute(f'ALTER TABLE "plantStress_soybean" ALTER COLUMN id DROP GENERATED BY DEFAULT AS IDENTITY;')  



