"""add potato cultivar table3

Revision ID: 54f33f0dc8a4
Revises: 80751d1ddb26
Create Date: 2026-01-14 02:10:46.628199

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54f33f0dc8a4'
down_revision = '80751d1ddb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
