"""Update nullable columns in g05_maize

Revision ID: 68f7836f9a3f
Revises: 8e3f7be7ad16
Create Date: 2026-01-15 21:43:19.528168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '68f7836f9a3f'
down_revision = '8e3f7be7ad16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g05_maize', 'g05_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('g05_maize', 'Date_Time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('g05_maize', 'Date_Time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('g05_maize', 'g05_maize_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
