"""Add missing tables disp, mulch and fertnut

Revision ID: 733581dc188a
Revises: 2d4e05df73d8
Create Date: 2026-01-11 20:26:16.140027

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '733581dc188a'
down_revision = '2d4e05df73d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classimVersion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispersivity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texturecl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertNutrient',
    sa.Column('fertilizationClass', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Nutrient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('fertilizationClass', 'Nutrient')
    )
    op.create_table('gas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('EPSI', sa.Float(), nullable=False),
    sa.Column('bTort', sa.Float(), nullable=False),
    sa.Column('Diffusion_Coeff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mulchDecomp',
    sa.Column('nutrient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contactFraction', sa.Float(), nullable=True),
    sa.Column('alphaFeeding', sa.Float(), nullable=True),
    sa.Column('carbMass', sa.Float(), nullable=True),
    sa.Column('cellMass', sa.Float(), nullable=True),
    sa.Column('lignMass', sa.Float(), nullable=True),
    sa.Column('carbNMass', sa.Float(), nullable=True),
    sa.Column('cellNMass', sa.Float(), nullable=True),
    sa.Column('lignNMass', sa.Float(), nullable=True),
    sa.Column('carbDecomp', sa.Float(), nullable=True),
    sa.Column('cellDecomp', sa.Float(), nullable=True),
    sa.Column('lignDecomp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nutrient')
    )
    op.create_table('mulchGeo',
    sa.Column('nutrient', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minHoriSize', sa.Float(), nullable=True),
    sa.Column('diffusionRestriction', sa.Float(), nullable=True),
    sa.Column('longWaveRadiationCtrl', sa.Float(), nullable=True),
    sa.Column('decompositionCtrl', sa.Float(), nullable=True),
    sa.Column('deltaRShort', sa.Float(), nullable=True),
    sa.Column('deltaRLong', sa.Float(), nullable=True),
    sa.Column('omega', sa.Float(), nullable=True),
    sa.Column('epsilonMulch', sa.Float(), nullable=True),
    sa.Column('alphaMulch', sa.Float(), nullable=True),
    sa.Column('maxStepInPicardIteration', sa.Float(), nullable=True),
    sa.Column('toleranceHead', sa.Float(), nullable=True),
    sa.Column('rhoMulch', sa.Float(), nullable=True),
    sa.Column('poreSpace', sa.Float(), nullable=True),
    sa.Column('maxPondingDepth', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nutrient')
    )
    op.add_column('pastruns', sa.Column('odate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastruns', 'odate')
    op.drop_table('mulchGeo')
    op.drop_table('mulchDecomp')
    op.drop_table('gas')
    op.drop_table('fertNutrient')
    op.drop_table('dispersivity')
    op.drop_table('classimVersion')
    # ### end Alembic commands ###
