"""changed class name for maizdata2

Revision ID: 76585fc5a140
Revises: e0db066b2de9
Create Date: 2026-01-12 17:42:29.488414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '76585fc5a140'
down_revision = 'e0db066b2de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
