"""add additional maize cultivar values

Revision ID: 77426ea435dc
Revises: 12d91303177a
Create Date: 2026-01-12 14:20:58.605517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77426ea435dc'
down_revision = '12d91303177a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivarmaize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hybridname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('juvenileleaves', sa.Float(), nullable=True),
    sa.Column('DaylengthSensitive', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('Rmax_LTAR', sa.Float(), server_default=sa.text('0.53'), nullable=True),
    sa.Column('Rmax_LTIR', sa.Float(), server_default=sa.text('0.978'), nullable=True),
    sa.Column('PhyllFrmTassel', sa.Float(), server_default=sa.text('3'), nullable=True),
    sa.Column('StayGreen', sa.Float(), server_default=sa.text('4.5'), nullable=True),
    sa.Column('LM_min', sa.Float(), server_default=sa.text('120'), nullable=True),
    sa.Column('RRRM', sa.Float(), server_default=sa.text('166.7'), nullable=True),
    sa.Column('RRRY', sa.Float(), server_default=sa.text('31.3'), nullable=True),
    sa.Column('RVRL', sa.Float(), server_default=sa.text('0.73'), nullable=True),
    sa.Column('ALPM', sa.Float(), server_default=sa.text('0.55'), nullable=True),
    sa.Column('ALPY', sa.Float(), server_default=sa.text('0.04'), nullable=True),
    sa.Column('RTWL', sa.Float(), server_default=sa.text('0.000106'), nullable=True),
    sa.Column('RTMinWTperArea', sa.Float(), server_default=sa.text('0.0002'), nullable=True),
    sa.Column('EPSI', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('IUPW', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('CourMax', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('Diffx', sa.Float(), server_default=sa.text('2.4'), nullable=True),
    sa.Column('Diffz', sa.Float(), server_default=sa.text('2.9'), nullable=True),
    sa.Column('VelZ', sa.Float(), server_default=sa.text('0'), nullable=True),
    sa.Column('lsink', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('Rroot', sa.Float(), server_default=sa.text('0.017'), nullable=True),
    sa.Column('Constl_M', sa.Float(), server_default=sa.text('35.0'), nullable=True),
    sa.Column('ConstK_M', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('Cmin0_M', sa.Float(), server_default=sa.text('0.01'), nullable=True),
    sa.Column('ConstI_Y', sa.Float(), server_default=sa.text('17.2'), nullable=True),
    sa.Column('ConstK_Y', sa.Float(), server_default=sa.text('0.75'), nullable=True),
    sa.Column('Cmin0_Y', sa.Float(), server_default=sa.text('0.03'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cultivar_maize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivar_maize',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hybridname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('juvenileleaves', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DaylengthSensitive', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('Rmax_LTAR', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.53'), autoincrement=False, nullable=True),
    sa.Column('Rmax_LTIR', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.978'), autoincrement=False, nullable=True),
    sa.Column('PhyllFrmTassel', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('StayGreen', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.5'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LM_min', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'120'::double precision"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('cultivar_maize_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cultivar_maize_pkey'))
    )
    op.drop_table('cultivarmaize')
    # ### end Alembic commands ###
