"""add output tables

Revision ID: 7ae9889b0fd7
Revises: db42deeabcb1
Create Date: 2026-01-14 18:05:00.098518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ae9889b0fd7'
down_revision = 'db42deeabcb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('g01_cotton',
    sa.Column('g01_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('PlantH', sa.Float(), nullable=True),
    sa.Column('LAI', sa.Float(), nullable=True),
    sa.Column('LInt', sa.Float(), nullable=True),
    sa.Column('Nodes', sa.Integer(), nullable=True),
    sa.Column('Sites', sa.Integer(), nullable=True),
    sa.Column('N_Squares', sa.Integer(), nullable=True),
    sa.Column('N_GB', sa.Integer(), nullable=True),
    sa.Column('N_OB', sa.Integer(), nullable=True),
    sa.Column('NLvsLoss', sa.Integer(), nullable=True),
    sa.Column('NSqLoss', sa.Integer(), nullable=True),
    sa.Column('NBollsLoss', sa.Integer(), nullable=True),
    sa.Column('NFruitShed', sa.Integer(), nullable=True),
    sa.Column('PetShd_DM', sa.Float(), nullable=True),
    sa.Column('GB_lossDM', sa.Float(), nullable=True),
    sa.Column('Lf_lossDM', sa.Float(), nullable=True),
    sa.Column('Rt_lossDM', sa.Float(), nullable=True),
    sa.Column('Dd_WtDM', sa.Float(), nullable=True),
    sa.Column('SquareDM', sa.Float(), nullable=True),
    sa.Column('GB_DM', sa.Float(), nullable=True),
    sa.Column('OB_DM', sa.Float(), nullable=True),
    sa.Column('LeafDM', sa.Float(), nullable=True),
    sa.Column('StemDM', sa.Float(), nullable=True),
    sa.Column('RootDM', sa.Float(), nullable=True),
    sa.Column('ResC', sa.Float(), nullable=True),
    sa.Column('PlantDM', sa.Float(), nullable=True),
    sa.Column('R_S', sa.Float(), nullable=True),
    sa.Column('Yield', sa.Float(), nullable=True),
    sa.Column('Temp', sa.Float(), nullable=True),
    sa.Column('L_Temp', sa.Float(), nullable=True),
    sa.Column('Rain', sa.Float(), nullable=True),
    sa.Column('SRad', sa.Integer(), nullable=True),
    sa.Column('PFD', sa.Float(), nullable=True),
    sa.Column('RH', sa.Float(), nullable=True),
    sa.Column('LeafN', sa.Float(), nullable=True),
    sa.Column('StemN', sa.Float(), nullable=True),
    sa.Column('SeedN', sa.Float(), nullable=True),
    sa.Column('BurrN', sa.Float(), nullable=True),
    sa.Column('RootN', sa.Float(), nullable=True),
    sa.Column('Nloss', sa.Float(), nullable=True),
    sa.Column('PlantN', sa.Float(), nullable=True),
    sa.Column('N_uptake', sa.Float(), nullable=True),
    sa.Column('S_Psi', sa.Float(), nullable=True),
    sa.Column('L_Psi', sa.Float(), nullable=True),
    sa.Column('LArea', sa.Float(), nullable=True),
    sa.Column('VPD', sa.Float(), nullable=True),
    sa.Column('StCond', sa.Float(), nullable=True),
    sa.Column('Pnet', sa.Float(), nullable=True),
    sa.Column('PGross', sa.Float(), nullable=True),
    sa.Column('L_Res', sa.Float(), nullable=True),
    sa.Column('Main_Res', sa.Float(), nullable=True),
    sa.Column('Resp', sa.Float(), nullable=True),
    sa.Column('SPnet', sa.Float(), nullable=True),
    sa.Column('C_Bal', sa.Float(), nullable=True),
    sa.Column('Nstress_Pn', sa.Float(), nullable=True),
    sa.Column('Note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('g01_cotton_id')
    )
    op.create_table('g01_soybean',
    sa.Column('g01_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jday', sa.Integer(), nullable=True),
    sa.Column('RSTAGE', sa.Float(), nullable=True),
    sa.Column('VSTAGE', sa.Float(), nullable=True),
    sa.Column('PFD', sa.Float(), nullable=True),
    sa.Column('SolRad', sa.Float(), nullable=True),
    sa.Column('Tair', sa.Float(), nullable=True),
    sa.Column('Tcan', sa.Float(), nullable=True),
    sa.Column('Pgross', sa.Float(), nullable=True),
    sa.Column('Pnet', sa.Float(), nullable=True),
    sa.Column('gs', sa.Float(), nullable=True),
    sa.Column('PSIL', sa.Float(), nullable=True),
    sa.Column('LAI', sa.Float(), nullable=True),
    sa.Column('LAREAT', sa.Float(), nullable=True),
    sa.Column('totalDM', sa.Float(), nullable=True),
    sa.Column('rootDM', sa.Float(), nullable=True),
    sa.Column('stemDM', sa.Float(), nullable=True),
    sa.Column('leafDM', sa.Float(), nullable=True),
    sa.Column('seedDM', sa.Float(), nullable=True),
    sa.Column('podDM', sa.Float(), nullable=True),
    sa.Column('DeadDM', sa.Float(), nullable=True),
    sa.Column('Tr_pot', sa.Float(), nullable=True),
    sa.Column('Tr_act', sa.Float(), nullable=True),
    sa.Column('wstress', sa.Float(), nullable=True),
    sa.Column('Nstress', sa.Float(), nullable=True),
    sa.Column('Limit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('g01_soybean_id')
    )
    op.create_table('g03_cotton',
    sa.Column('g03_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('hNew', sa.Float(), nullable=True),
    sa.Column('thNew', sa.Float(), nullable=True),
    sa.Column('Q', sa.Float(), nullable=True),
    sa.Column('NO3N', sa.Float(), nullable=True),
    sa.Column('NH4N', sa.Float(), nullable=True),
    sa.Column('Temp', sa.Float(), nullable=True),
    sa.Column('CO2Conc', sa.Float(), nullable=True),
    sa.Column('O2Conc', sa.Float(), nullable=True),
    sa.Column('N2OConc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g03_cotton_id')
    )
    op.create_table('g03_fallow',
    sa.Column('g03_fallow_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sa.Float(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('hNew', sa.Float(), nullable=True),
    sa.Column('thNew', sa.Float(), nullable=True),
    sa.Column('Q', sa.Float(), nullable=True),
    sa.Column('NO3N', sa.Float(), nullable=True),
    sa.Column('NH4N', sa.Float(), nullable=True),
    sa.Column('Temp', sa.Float(), nullable=True),
    sa.Column('CO2Conc', sa.Float(), nullable=True),
    sa.Column('O2Conc', sa.Integer(), nullable=True),
    sa.Column('N2OConc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g03_fallow_id')
    )
    op.create_table('g03_soybean',
    sa.Column('g03_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('hNew', sa.Float(), nullable=True),
    sa.Column('thNew', sa.Float(), nullable=True),
    sa.Column('Q', sa.Float(), nullable=True),
    sa.Column('NO3N', sa.Float(), nullable=True),
    sa.Column('NH4N', sa.Float(), nullable=True),
    sa.Column('Temp', sa.Float(), nullable=True),
    sa.Column('CO2Conc', sa.Float(), nullable=True),
    sa.Column('O2Conc', sa.Float(), nullable=True),
    sa.Column('N2OConc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g03_soybean_id')
    )
    op.create_table('g04_cotton',
    sa.Column('g04_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('Node', sa.Integer(), nullable=True),
    sa.Column('RMassM', sa.Float(), nullable=True),
    sa.Column('RMassY', sa.Float(), nullable=True),
    sa.Column('RDenM', sa.Float(), nullable=True),
    sa.Column('RDenY', sa.Float(), nullable=True),
    sa.Column('WaterSink', sa.Float(), nullable=True),
    sa.Column('NitSink', sa.Float(), nullable=True),
    sa.Column('GasSink', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g04_cotton_id')
    )
    op.create_table('g04_soybean',
    sa.Column('g04_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('Node', sa.Integer(), nullable=True),
    sa.Column('RMassM', sa.Float(), nullable=True),
    sa.Column('RMassY', sa.Float(), nullable=True),
    sa.Column('RDenM', sa.Float(), nullable=True),
    sa.Column('RDenY', sa.Float(), nullable=True),
    sa.Column('WaterSink', sa.Float(), nullable=True),
    sa.Column('NitSink', sa.Float(), nullable=True),
    sa.Column('GasSink', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g04_soybean_id')
    )
    op.create_table('g05_cotton',
    sa.Column('g05_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PSoilEvap', sa.Float(), nullable=True),
    sa.Column('ASoilEVap', sa.Float(), nullable=True),
    sa.Column('PET_PEN', sa.Float(), nullable=True),
    sa.Column('PE_T_int', sa.Float(), nullable=True),
    sa.Column('transp', sa.Float(), nullable=True),
    sa.Column('CumRain', sa.Float(), nullable=True),
    sa.Column('infil', sa.Float(), nullable=True),
    sa.Column('FLuxAct', sa.Float(), nullable=True),
    sa.Column('Drainage', sa.Float(), nullable=True),
    sa.Column('N_Leach', sa.Float(), nullable=True),
    sa.Column('Runoff', sa.Float(), nullable=True),
    sa.Column('cover', sa.Float(), nullable=True),
    sa.Column('PSIM', sa.Float(), nullable=True),
    sa.Column('SeasPSoEv', sa.Float(), nullable=True),
    sa.Column('SeasASoEv', sa.Float(), nullable=True),
    sa.Column('SeasPTran', sa.Float(), nullable=True),
    sa.Column('SeasATran', sa.Float(), nullable=True),
    sa.Column('SeasRain', sa.Float(), nullable=True),
    sa.Column('SeasInfil', sa.Float(), nullable=True),
    sa.Column('ThetaAvail', sa.Float(), nullable=True),
    sa.Column('CO2FLux', sa.Float(), nullable=True),
    sa.Column('O2FLux', sa.Float(), nullable=True),
    sa.Column('N2OFLux', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g05_cotton_id')
    )
    op.create_table('g05_fallow',
    sa.Column('g05_fallow_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sa.Float(), nullable=True),
    sa.Column('PSoilEvap', sa.Float(), nullable=True),
    sa.Column('ASoilEVap', sa.Float(), nullable=True),
    sa.Column('PET_PEN', sa.Float(), nullable=True),
    sa.Column('PE_T_int', sa.Float(), nullable=True),
    sa.Column('transp', sa.Float(), nullable=True),
    sa.Column('CumRain', sa.Float(), nullable=True),
    sa.Column('infil', sa.Float(), nullable=True),
    sa.Column('FLuxAct', sa.Float(), nullable=True),
    sa.Column('Drainage', sa.Float(), nullable=True),
    sa.Column('N_Leach', sa.Float(), nullable=True),
    sa.Column('Runoff', sa.Float(), nullable=True),
    sa.Column('cover', sa.Float(), nullable=True),
    sa.Column('PSIM', sa.Float(), nullable=True),
    sa.Column('SeasPSoEv', sa.Float(), nullable=True),
    sa.Column('SeasASoEv', sa.Float(), nullable=True),
    sa.Column('SeasPTran', sa.Float(), nullable=True),
    sa.Column('SeasATran', sa.Float(), nullable=True),
    sa.Column('SeasRain', sa.Float(), nullable=True),
    sa.Column('SeasInfil', sa.Float(), nullable=True),
    sa.Column('ThetaAvail', sa.Float(), nullable=True),
    sa.Column('CO2FLux', sa.Float(), nullable=True),
    sa.Column('O2FLux', sa.Float(), nullable=True),
    sa.Column('N2OFLux', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g05_fallow_id')
    )
    op.create_table('g05_soybean',
    sa.Column('g05_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PSoilEvap', sa.Float(), nullable=True),
    sa.Column('ASoilEVap', sa.Float(), nullable=True),
    sa.Column('PET_PEN', sa.Float(), nullable=True),
    sa.Column('PE_T_int', sa.Float(), nullable=True),
    sa.Column('transp', sa.Float(), nullable=True),
    sa.Column('CumRain', sa.Float(), nullable=True),
    sa.Column('infil', sa.Float(), nullable=True),
    sa.Column('FLuxAct', sa.Float(), nullable=True),
    sa.Column('Drainage', sa.Float(), nullable=True),
    sa.Column('N_Leach', sa.Float(), nullable=True),
    sa.Column('Runoff', sa.Float(), nullable=True),
    sa.Column('cover', sa.Float(), nullable=True),
    sa.Column('PSIM', sa.Float(), nullable=True),
    sa.Column('SeasPSoEv', sa.Float(), nullable=True),
    sa.Column('SeasASoEv', sa.Float(), nullable=True),
    sa.Column('SeasPTran', sa.Float(), nullable=True),
    sa.Column('SeasATran', sa.Float(), nullable=True),
    sa.Column('SeasRain', sa.Float(), nullable=True),
    sa.Column('SeasInfil', sa.Float(), nullable=True),
    sa.Column('ThetaAvail', sa.Float(), nullable=True),
    sa.Column('CO2FLux', sa.Float(), nullable=True),
    sa.Column('O2FLux', sa.Float(), nullable=True),
    sa.Column('N2OFLux', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g05_soybean_id')
    )
    op.create_table('g07_cotton',
    sa.Column('g07_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('Humus_N', sa.Float(), nullable=True),
    sa.Column('Humus_C', sa.Float(), nullable=True),
    sa.Column('Litter_N', sa.Float(), nullable=True),
    sa.Column('Litter_C', sa.Float(), nullable=True),
    sa.Column('Manure_N', sa.Float(), nullable=True),
    sa.Column('Manure_C', sa.Float(), nullable=True),
    sa.Column('Root_N', sa.Float(), nullable=True),
    sa.Column('Root_C', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g07_cotton_id')
    )
    op.create_table('g07_fallow',
    sa.Column('g07_fallow_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('Humus_N', sa.Float(), nullable=True),
    sa.Column('Humus_C', sa.Float(), nullable=True),
    sa.Column('Litter_N', sa.Float(), nullable=True),
    sa.Column('Litter_C', sa.Float(), nullable=True),
    sa.Column('Manure_N', sa.Float(), nullable=True),
    sa.Column('Manure_C', sa.Float(), nullable=True),
    sa.Column('Root_N', sa.Float(), nullable=True),
    sa.Column('Root_C', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g07_fallow_id')
    )
    op.create_table('g07_soybean',
    sa.Column('g07_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('X', sa.Float(), nullable=True),
    sa.Column('Y', sa.Float(), nullable=True),
    sa.Column('Humus_N', sa.Float(), nullable=True),
    sa.Column('Humus_C', sa.Float(), nullable=True),
    sa.Column('Litter_N', sa.Float(), nullable=True),
    sa.Column('Litter_C', sa.Float(), nullable=True),
    sa.Column('Manure_N', sa.Float(), nullable=True),
    sa.Column('Manure_C', sa.Float(), nullable=True),
    sa.Column('Root_N', sa.Float(), nullable=True),
    sa.Column('Root_C', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('g07_soybean_id')
    )
    op.create_table('nitrogen_soybean',
    sa.Column('nitrogen_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=False),
    sa.Column('total_N', sa.Float(), nullable=True),
    sa.Column('leaf_N', sa.Float(), nullable=True),
    sa.Column('stem_N', sa.Float(), nullable=True),
    sa.Column('pod_N', sa.Float(), nullable=True),
    sa.Column('seed_N', sa.Float(), nullable=True),
    sa.Column('root_N', sa.Float(), nullable=True),
    sa.Column('dead_N', sa.Float(), nullable=True),
    sa.Column('plant_N_C', sa.Float(), nullable=True),
    sa.Column('N_uptake', sa.Float(), nullable=True),
    sa.Column('N_demand', sa.Float(), nullable=True),
    sa.Column('Nstress', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nitrogen_soybean_id')
    )
    op.create_table('plantStress_cotton',
    sa.Column('plantStress_cotton_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=False),
    sa.Column('W_stress', sa.Float(), nullable=True),
    sa.Column('N_Veg_Str', sa.Float(), nullable=True),
    sa.Column('N_Fru_Str', sa.Float(), nullable=True),
    sa.Column('N_Rt_Str', sa.Float(), nullable=True),
    sa.Column('C_Stress', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('plantStress_cotton_id')
    )
    op.create_table('plantStress_fallow',
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('waterstress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('N_stress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Shade_Stress', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('PotentialArea', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plantStress_fallow_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('plantStress_fallow_id')
    )
    op.create_table('plantStress_soybean',
    sa.Column('plantStress_soybean_id', sa.Integer(), nullable=False),
    sa.Column('Date_Time', sa.DateTime(), nullable=False),
    sa.Column('wstress', sa.Float(), nullable=True),
    sa.Column('Nstress', sa.Float(), nullable=True),
    sa.Column('Cstress', sa.Float(), nullable=True),
    sa.Column('NEffect_ve', sa.Float(), nullable=True),
    sa.Column('wstress2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('plantStress_soybean_id')
    )
    op.drop_table('geometry')
    op.alter_column('PGRUnit', 'code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('g01_maize', sa.Column('grainDM', sa.Float(), nullable=True))
    op.alter_column('g01_maize', 'g01_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g01_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'jday',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'MaturLvs',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'Dropped',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'Note',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('g01_potato', sa.Column('Rg_Rm', sa.Float(), nullable=True))
    op.add_column('g01_potato', sa.Column('Tr_Pot', sa.Float(), nullable=True))
    op.add_column('g01_potato', sa.Column('Tr_Act', sa.Float(), nullable=True))
    op.alter_column('g01_potato', 'g01_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g01_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('g01_potato', 'jday',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_column('g01_potato', 'Tr-Act')
    op.drop_column('g01_potato', 'Rg+Rm')
    op.drop_column('g01_potato', 'Tr-Pot')
    op.add_column('g03_maize', sa.Column('Humus_N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Humus_C', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Litter_N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Litter_C', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Manure_N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Manure_C', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Root_N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Root_C', sa.Float(), nullable=True))
    op.alter_column('g03_maize', 'g03_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g03_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('g03_maize', 'Temp')
    op.drop_column('g03_maize', 'NH4N')
    op.drop_column('g03_maize', 'N2OConc')
    op.drop_column('g03_maize', 'O2Conc')
    op.drop_column('g03_maize', 'Q')
    op.drop_column('g03_maize', 'NO3N')
    op.drop_column('g03_maize', 'CO2Conc')
    op.drop_column('g03_maize', 'hNew')
    op.drop_column('g03_maize', 'thNew')
    op.add_column('g03_potato', sa.Column('Humus_N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Humus_C', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Litter_N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Litter_C', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Manure_N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Manure_C', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Root_N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Root_C', sa.Float(), nullable=True))
    op.alter_column('g03_potato', 'g03_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g03_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_column('g03_potato', 'Temp')
    op.drop_column('g03_potato', 'NH4N')
    op.drop_column('g03_potato', 'N2OConc')
    op.drop_column('g03_potato', 'O2Conc')
    op.drop_column('g03_potato', 'Q')
    op.drop_column('g03_potato', 'NO3N')
    op.drop_column('g03_potato', 'CO2Conc')
    op.drop_column('g03_potato', 'hNew')
    op.drop_column('g03_potato', 'thNew')
    op.alter_column('g04_maize', 'g04_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g04_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('g04_maize', 'Node',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('g04_potato', 'g04_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g04_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('g04_potato', 'Node',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g05_maize', 'g05_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g05_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('g05_potato', 'g05_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g05_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('g07_maize', 'g07_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g07_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('g07_potato', 'g07_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('g07_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('nitrogen_potato', 'nitrogen_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('nitrogen_potato','Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               postgresql_using='EXTRACT(EPOCH FROM "Date_Time")::integer',
               existing_nullable=True
)
    op.alter_column('plantStress_maize', 'plantStress_maize_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('plantStress_maize', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('plantStress_potato', 'plantStress_potato_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('plantStress_potato', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('plantStress_potato', 'PSIEffect_leaf',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plantStress_potato', 'PSIEffect_leaf',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('plantStress_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('plantStress_potato', 'plantStress_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('plantStress_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('plantStress_maize', 'plantStress_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('nitrogen_potato', 'Date_Time',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('nitrogen_potato', 'nitrogen_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g07_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g07_potato', 'g07_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g07_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g07_maize', 'g07_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g05_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('g05_potato', 'g05_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g05_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('g05_maize', 'g05_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g04_potato', 'Node',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g04_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g04_potato', 'g04_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('g04_maize', 'Node',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g04_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g04_maize', 'g04_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.add_column('g03_potato', sa.Column('thNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('hNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('CO2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('NO3N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Q', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('O2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('N2OConc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('NH4N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('g03_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g03_potato', 'g03_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('g03_potato', 'Root_C')
    op.drop_column('g03_potato', 'Root_N')
    op.drop_column('g03_potato', 'Manure_C')
    op.drop_column('g03_potato', 'Manure_N')
    op.drop_column('g03_potato', 'Litter_C')
    op.drop_column('g03_potato', 'Litter_N')
    op.drop_column('g03_potato', 'Humus_C')
    op.drop_column('g03_potato', 'Humus_N')
    op.add_column('g03_maize', sa.Column('thNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('hNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('CO2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('NO3N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Q', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('O2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('N2OConc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('NH4N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('g03_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g03_maize', 'g03_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('g03_maize', 'Root_C')
    op.drop_column('g03_maize', 'Root_N')
    op.drop_column('g03_maize', 'Manure_C')
    op.drop_column('g03_maize', 'Manure_N')
    op.drop_column('g03_maize', 'Litter_C')
    op.drop_column('g03_maize', 'Litter_N')
    op.drop_column('g03_maize', 'Humus_C')
    op.drop_column('g03_maize', 'Humus_N')
    op.add_column('g01_potato', sa.Column('Tr-Pot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g01_potato', sa.Column('Rg+Rm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g01_potato', sa.Column('Tr-Act', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('g01_potato', 'jday',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('g01_potato', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('g01_potato', 'g01_potato_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('g01_potato', 'Tr_Act')
    op.drop_column('g01_potato', 'Tr_Pot')
    op.drop_column('g01_potato', 'Rg_Rm')
    op.alter_column('g01_maize', 'Note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'Dropped',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'MaturLvs',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'jday',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g01_maize', 'g01_maize_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('g01_maize', 'grainDM')
    op.alter_column('PGRUnit', 'code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('geometry',
    sa.Column('nodeNum', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('X', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Layer', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N2OConc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('simID', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('plantStress_soybean')
    op.drop_table('plantStress_fallow')
    op.drop_table('plantStress_cotton')
    op.drop_table('nitrogen_soybean')
    op.drop_table('g07_soybean')
    op.drop_table('g07_fallow')
    op.drop_table('g07_cotton')
    op.drop_table('g05_soybean')
    op.drop_table('g05_fallow')
    op.drop_table('g05_cotton')
    op.drop_table('g04_soybean')
    op.drop_table('g04_cotton')
    op.drop_table('g03_soybean')
    op.drop_table('g03_fallow')
    op.drop_table('g03_cotton')
    op.drop_table('g01_soybean')
    op.drop_table('g01_cotton')
    # ### end Alembic commands ###
