"""adding_soil_long_table

Revision ID: 7f30e82c38bb
Revises: 381387ae589a
Create Date: 2024-05-20 12:37:06.661481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f30e82c38bb'
down_revision = '381387ae589a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_long',
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.Column("o_sid", sa.Integer(), nullable=False),
        sa.Column("Bottom_depth", sa.Float(), nullable=False),
        sa.Column("OM_pct", sa.Float(), nullable=False),
        sa.Column("NO3", sa.Float(), nullable=False),
        sa.Column("NH4", sa.Float(), nullable=False),
        sa.Column("HnNew", sa.Float(), nullable=False),
        sa.Column("initType", sa.Integer(), nullable=False,server_default= "1"),
        sa.Column("Tmpr", sa.Float(), nullable=False),
        sa.Column("Sand", sa.Float(), nullable=False),
        sa.Column("Silt", sa.Float(), nullable=False),
        sa.Column("Clay", sa.Float(), nullable=False),
        sa.Column("BD", sa.REAL(), nullable=False),
        sa.Column("TH33", sa.Float(), nullable=False),
        sa.Column("TH1500", sa.Float(), nullable=False),
        sa.Column("thr", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("ths", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("tha", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("th", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("Alfa", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("n", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("Ks", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("Kk", sa.Float(), nullable=False, server_default= "-1"),
        sa.Column("thk", sa.Float(), nullable=False, server_default= "-1"),


        sa.Column("kl", sa.Float(), nullable=False,server_default= "-0.035"),
        sa.Column("kh", sa.Float(), nullable=False,server_default= "-0.00007"),
        sa.Column("km", sa.Float(), nullable=False,server_default= "0.07"),
        sa.Column("kn", sa.Float(), nullable=False,server_default= "0.2"),
        sa.Column("kd", sa.Float(), nullable=False,server_default= "0.00001"),
        sa.Column("fe", sa.Float(), nullable=False,server_default= "0.6"),
        sa.Column("fh", sa.Float(), nullable=False,server_default= "0.2"),
        sa.Column("r0", sa.Float(), nullable=False,server_default= "10.0"),
        sa.Column("rL", sa.Float(), nullable=False,server_default= "50.0"),
        sa.Column("rm", sa.Float(), nullable=False,server_default= "10.0"),
        sa.Column("fa", sa.Float(), nullable=False,server_default= "0.1"),
        sa.Column("nq", sa.Float(), nullable=False,server_default= "8"),
        sa.Column("cs", sa.Float(), nullable=False,server_default= "0.00001"),
        sa.Column("CO2", sa.REAL(), nullable=False, server_default= "400"),
        sa.Column("O2", sa.REAL(), nullable=False, server_default= "206000"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.droptable("soil_long")