"""add potato cultivar table

Revision ID: 82cd53a23e87
Revises: 32afebb24dc0
Create Date: 2026-01-14 01:51:44.501770

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82cd53a23e87'
down_revision = '32afebb24dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('g04_maize')
    op.drop_table('g05_maize')
    op.drop_table('g03_maize')
    op.drop_table('geometry')
    op.drop_table('plantStress_maize')
    op.drop_table('g07_maize')
    op.drop_table('g01_maize')
    op.add_column('cultivar_potato', sa.Column('RRRM', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('RRRY', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('RVRL', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('ALPM', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('ALPY', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('RTWL', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('RTMinWTperArea', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('EPSI', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('IUPW', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('CourMax', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Diffx', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Diffz', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('VelZ', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('lsink', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Rroot', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Consl_M', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('ConstK_M', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Cmin0_M', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('ConstI_Y', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('ConstK_Y', sa.Float(), nullable=False))
    op.add_column('cultivar_potato', sa.Column('Cmin0_Y', sa.Float(), nullable=False))
    op.alter_column('cultivar_potato', 'hybridname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('cultivar_potato', 'A1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'A6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'A8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'A9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'A10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'G1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'G2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'G3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'G4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('cultivar_potato', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cultivar_potato', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cultivar_potato', 'G4',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'G3',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'G2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'G1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'A10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'A9',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'A8',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'A6',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'A1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cultivar_potato', 'hybridname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cultivar_potato', 'Cmin0_Y')
    op.drop_column('cultivar_potato', 'ConstK_Y')
    op.drop_column('cultivar_potato', 'ConstI_Y')
    op.drop_column('cultivar_potato', 'Cmin0_M')
    op.drop_column('cultivar_potato', 'ConstK_M')
    op.drop_column('cultivar_potato', 'Consl_M')
    op.drop_column('cultivar_potato', 'Rroot')
    op.drop_column('cultivar_potato', 'lsink')
    op.drop_column('cultivar_potato', 'VelZ')
    op.drop_column('cultivar_potato', 'Diffz')
    op.drop_column('cultivar_potato', 'Diffx')
    op.drop_column('cultivar_potato', 'CourMax')
    op.drop_column('cultivar_potato', 'IUPW')
    op.drop_column('cultivar_potato', 'EPSI')
    op.drop_column('cultivar_potato', 'RTMinWTperArea')
    op.drop_column('cultivar_potato', 'RTWL')
    op.drop_column('cultivar_potato', 'ALPY')
    op.drop_column('cultivar_potato', 'ALPM')
    op.drop_column('cultivar_potato', 'RVRL')
    op.drop_column('cultivar_potato', 'RRRY')
    op.drop_column('cultivar_potato', 'RRRM')
    op.create_table('g01_maize',
    sa.Column('jday', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Leaves', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('MaturLvs', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Dropped', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('LA_pl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LA_dead', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LAI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LeafWP', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PFD', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SolRad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SoilT', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Tair', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Tcan', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ETdmd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ETsply', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Pn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Pg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Respir', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('av_gs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('VPD', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Nitr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N_Dem', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NUpt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LeafN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PCRL', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('totalDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shootDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('earDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('TotLeafDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('DrpLfDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stemDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rootDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SoilRt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('MxRtDep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AvailW', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('solubleC', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('g01_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('g07_maize',
    sa.Column('X', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Humus_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Humus_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Litter_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Litter_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Manure_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Manure_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Root_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Root_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g07_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('plantStress_maize',
    sa.Column('waterstress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N_stress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Shade_Stress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PotentialArea', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('plantStress_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('geometry',
    sa.Column('nodeNum', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('X', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Layer', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N2OConc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('simID', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('g03_maize',
    sa.Column('X', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('thNew', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Q', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NO3N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NH4N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CO2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('O2Conc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N2OConc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g03_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('g05_maize',
    sa.Column('PSoilEvap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ASoilEVap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PET_PEN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PE_T_int', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CumRain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('infil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('FLuxAct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Drainage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N_Leach', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Runoff', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cover', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PSIM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasPSoEv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasASoEv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasPTran', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasATran', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasRain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeasInfil', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ThetaAvail', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CO2FLux', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('O2FLux', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N2OFLux', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g05_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('g04_maize',
    sa.Column('X', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Node', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('RMassM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RMassY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RDenM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RDenY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('WaterSink', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NitSink', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GasSink', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('g04_maize_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Date_Time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
