"""remove key param from id field for output files

Revision ID: 8e3f7be7ad16
Revises: bcfdbf1e7fea
Create Date: 2026-01-15 18:28:34.291682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e3f7be7ad16'
down_revision = 'bcfdbf1e7fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('g01cotton')
    op.add_column('g01_cotton', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('g01_cotton', 'g01_cotton_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Date_Time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Nodes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Sites',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_Squares',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_GB',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_OB',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NLvsLoss',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NSqLoss',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NBollsLoss',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NFruitShed',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'SRad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Note',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('g01_maize', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('g01_maize', 'g01_maize_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('g01_potato', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('g01_potato', 'g01_potato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    op.add_column('g01_soybean', sa.Column('id', sa.Integer(), nullable=False))
   # op.alter_column('g01_soybean', 'g01_soybean_id',
   #            existing_type=sa.INTEGER(),
   #            nullable=True)

    # 1. Drop the old primary key constraint
    op.drop_constraint('g01_soybean_pkey', 'g01_soybean', type_='primary')

# 2. Add the new primary key constraint on 'id'
    op.create_primary_key('g01_soybean_pkey', 'g01_soybean', ['id'])

# 3. Alter 'g01_soybean_id' to be nullable
    op.alter_column('g01_soybean', 'g01_soybean_id', nullable=True)

    op.add_column('g03_cotton', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g03_cotton_pkey', 'g03_cotton', type_='primary')
    op.create_primary_key('g03_cotton_pkey', 'g03_cotton', ['id'])
    op.alter_column('g03_cotton', 'g03_cotton_id', nullable=True)
#    op.alter_column('g03_cotton', 'g03_cotton_id',
#               existing_type=sa.INTEGER(),
#               nullable=True)
    op.add_column('g03_fallow', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('g03_maize', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('g03_maize', sa.Column('hNew', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('thNew', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Q', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('NO3N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('NH4N', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('Temp', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('CO2Conc', sa.Float(), nullable=True))
    op.add_column('g03_maize', sa.Column('O2Conc', sa.Integer(), nullable=True))
    op.add_column('g03_maize', sa.Column('N2OConc', sa.Float(), nullable=True))
    op.alter_column('g03_maize', 'g03_maize_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('g03_maize', 'Manure_N')
    op.drop_column('g03_maize', 'Manure_C')
    op.drop_column('g03_maize', 'Humus_N')
    op.drop_column('g03_maize', 'Litter_C')
    op.drop_column('g03_maize', 'Humus_C')
    op.drop_column('g03_maize', 'Root_N')
    op.drop_column('g03_maize', 'Root_C')
    op.drop_column('g03_maize', 'Litter_N')
    op.add_column('g03_potato', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('g03_potato', sa.Column('hNew', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('thNew', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Q', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('NO3N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('NH4N', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('Temp', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('CO2Conc', sa.Float(), nullable=True))
    op.add_column('g03_potato', sa.Column('O2Conc', sa.Integer(), nullable=True))
    op.add_column('g03_potato', sa.Column('N2OConc', sa.Float(), nullable=True))
    op.alter_column('g03_potato', 'g03_potato_id',
               existing_type=sa.INTEGER(),
               nullable=True)
  #  op.alter_column('g03_potato', 'Date_Time',
  #             existing_type=sa.VARCHAR(),
  #             type_=sa.Float(),
  #             existing_nullable=True)
    op.drop_column('g03_potato', 'Manure_N')
    op.drop_column('g03_potato', 'Manure_C')
    op.drop_column('g03_potato', 'Humus_N')
    op.drop_column('g03_potato', 'Litter_C')
    op.drop_column('g03_potato', 'Humus_C')
    op.drop_column('g03_potato', 'Root_N')
    op.drop_column('g03_potato', 'Root_C')
    op.drop_column('g03_potato', 'Litter_N')

    op.add_column('g03_soybean', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g03_soybean_pkey', 'g03_soybean', type_='primary')
    op.create_primary_key('g03_soybean_pkey', 'g03_soybean', ['id'])
    op.alter_column('g03_soybean', 'g03_soybean_id', nullable=True)
   # op.alter_column('g03_soybean', 'g03_soybean_id',
   #            existing_type=sa.INTEGER(),
   #            nullable=True)
    op.add_column('g04_cotton', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g04_cotton_pkey', 'g04_cotton', type_='primary')
    op.create_primary_key('g04_cotton_pkey', 'g04_cotton', ['id'])
    op.alter_column('g04_cotton', 'g04_cotton_id', nullable=True)   
   
    op.add_column('g04_maize', sa.Column('id', sa.Integer(), nullable=False))
   # op.drop_constraint('g04_maize_pkey', 'g04_maize', type_='primary')
    op.create_primary_key('g04_maize_pkey', 'g04_maize', ['id'])
    op.alter_column('g04_maize', 'g04_maize_id', nullable=True)   

    #op.alter_column('g04_maize', 'g04_maize_id',
    #           existing_type=sa.INTEGER(),
    #           nullable=True)

    op.add_column('g04_potato', sa.Column('id', sa.Integer(), nullable=False))
  #  op.drop_constraint('g04_potato_pkey', 'g04_potato', type_='primary')
    op.create_primary_key('g04_potato_pkey', 'g04_potato', ['id'])
    op.alter_column('g04_potato', 'g04_potato_id', nullable=True)    
      # op.alter_column('g04_potato', 'g04_potato_id',
   #            existing_type=sa.INTEGER(),
   #            nullable=True)

    op.add_column('g04_soybean', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g04_soybean_pkey', 'g04_soybean', type_='primary')
    op.create_primary_key('g04_soybean_pkey', 'g04_soybean', ['id'])
    op.alter_column('g04_soybean', 'g04_soybean_id', nullable=True)    
   # op.alter_column('g04_soybean', 'g04_soybean_id',
   #            existing_type=sa.INTEGER(),
   #            nullable=True)

    op.add_column('g05_cotton', sa.Column('id', sa.Integer(), nullable=False))

    op.add_column('g05_fallow', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g05_fallow_pkey', 'g05_fallow', type_='primary')
    op.create_primary_key('g05_fallow_pkey', 'g05_fallow', ['id']) 
    op.alter_column('g05_fallow', 'g05_fallow_id', nullable=True)       
  #  op.alter_column('g05_fallow', 'g05_fallow_id',
  #             existing_type=sa.INTEGER(),
  #             nullable=True)

    op.add_column('g05_maize', sa.Column('id', sa.Integer(), nullable=False))
  #  op.drop_constraint('g05_maize_pkey', 'g05_maize', type_='primary')
    op.create_primary_key('g05_maize_pkey', 'g05_maize', ['id'])
    op.alter_column('g05_maize', 'g05_maize_id', nullable=True)        
    #op.alter_column('g05_maize', 'Date_Time',
  #           existing_type=sa.VARCHAR(),
   #            nullable=True)
    
    op.add_column('g05_potato', sa.Column('id', sa.Integer(), nullable=False))
 #   op.drop_constraint('g05_potato_pkey', 'g05_potato', type_='primary')
    op.create_primary_key('g05_potato_pkey', 'g05_potato', ['id'])
    op.alter_column('g05_potato', 'g05_potato_id', nullable=True)    
 #   op.alter_column('g05_potato', 'g05_potato_id',
 #              existing_type=sa.INTEGER(),
 #              nullable=True)
    
    op.add_column('g05_soybean', sa.Column('id', sa.Integer(), nullable=False))

    op.add_column('g07_cotton', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g07_cotton_pkey', 'g07_cotton', type_='primary')
    op.create_primary_key('g07_cotton_pkey', 'g07_cotton', ['id'])
    op.alter_column('g07_cotton', 'g07_cotton_id', nullable=True)    

  #  op.alter_column('g07_cotton', 'g07_cotton_id',
  #             existing_type=sa.INTEGER(),
  #             nullable=True)

    op.add_column('g07_fallow', sa.Column('id', sa.Integer(), nullable=False))

    op.add_column('g07_maize', sa.Column('id', sa.Integer(), nullable=False))
#    op.drop_constraint('g07_maize_pkey', 'g07_maize', type_='primary')
    op.create_primary_key('g07_maize_pkey', 'g07_maize', ['id'])
    op.alter_column('g07_maize', 'g07_maize_id', nullable=True)    
 #   op.alter_column('g07_maize', 'g07_maize_id',
 #              existing_type=sa.INTEGER(),
 #              nullable=True)

    op.add_column('g07_potato', sa.Column('id', sa.Integer(), nullable=False))
#    op.drop_constraint('g07_potato_pkey', 'g07_potato', type_='primary')
    op.create_primary_key('g07_potato_pkey', 'g07_potato', ['id']) 
    op.alter_column('g07_potato', 'g07_potato_id', nullable=True)      
 #   op.alter_column('g07_potato', 'g07_potato_id',
 #              existing_type=sa.INTEGER(),
 #              nullable=True)
    
    op.add_column('g07_soybean', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('g07_soybean_pkey', 'g07_soybean', type_='primary')
    op.create_primary_key('g07_soybean_pkey', 'g07_soybean', ['id'])
    op.alter_column('g07_soybean', 'g07_soybean_id', nullable=True)       
 #   op.alter_column('g07_soybean', 'g07_soybean_id',
 #              existing_type=sa.INTEGER(),
 #              nullable=True)
    
    op.add_column('nitrogen_potato', sa.Column('id', sa.Integer(), nullable=False))
 #   op.drop_constraint('nitrogen_potato_pkey', 'nitrogen_potato', type_='primary')
    op.create_primary_key('nitrogen_potato_pkey', 'nitrogen_potato', ['id'])
    op.alter_column('nitrogen_potato', 'nitrogen_potato_id', nullable=True)    
  #  op.alter_column('nitrogen_potato', 'nitrogen_potato_id',
  #             existing_type=sa.INTEGER(),
  #             nullable=True)

    op.add_column('nitrogen_soybean', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('plantStress_cotton', sa.Column('id', sa.Integer(), nullable=False))

    op.add_column('plantStress_fallow', sa.Column('id', sa.Integer(), nullable=False))

    op.drop_constraint('plantStress_fallow_pkey', 'plantStress_fallow', type_='primary')
    op.create_primary_key('plantStress_fallow_pkey', 'plantStress_fallow', ['id'])
    op.alter_column('plantStress_fallow', 'plantStress_fallow_id', nullable=True)    
   # op.alter_column('plantStress_fallow', 'plantStress_fallow_id',
   #            existing_type=sa.INTEGER(),
   #            nullable=True)

    op.add_column('plantStress_maize', sa.Column('id', sa.Integer(), nullable=False))
  #  op.drop_constraint('plantStress_maize_pkey', 'plantStress_maize', type_='primary')
    op.create_primary_key('plantStress_maize_pkey', 'plantStress_maize', ['id'])
    op.alter_column('plantStress_maize', 'plantStress_maize_id', nullable=True)        
  #  op.alter_column('plantStress_maize', 'plantStress_maize_id',
  #             existing_type=sa.INTEGER(),
  #             nullable=True)
    op.alter_column('plantStress_maize', 'Date_Time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    op.add_column('plantStress_potato', sa.Column('id', sa.Integer(), nullable=False))
 #   op.drop_constraint('plantStress_potato_pkey', 'plantStress_potato', type_='primary')
    op.create_primary_key('plantStress_potato_pkey', 'plantStress_potato', ['id'])
    op.alter_column('plantStress_potato', 'plantStress_potato_id', nullable=True)    
 #   op.alter_column('plantStress_potato', 'plantStress_potato_id',
 #              existing_type=sa.INTEGER(),
 #              nullable=True)
    op.add_column('plantStress_soybean', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantStress_soybean', 'id')
    op.alter_column('plantStress_potato', 'plantStress_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plantStress_potato', 'id')
    op.alter_column('plantStress_maize', 'Date_Time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('plantStress_maize', 'plantStress_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plantStress_maize', 'id')
    op.alter_column('plantStress_fallow', 'plantStress_fallow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plantStress_fallow', 'id')
    op.drop_column('plantStress_cotton', 'id')
    op.drop_column('nitrogen_soybean', 'id')
    op.alter_column('nitrogen_potato', 'nitrogen_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('nitrogen_potato', 'id')
    op.alter_column('g07_soybean', 'g07_soybean_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g07_soybean', 'id')
    op.alter_column('g07_potato', 'g07_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g07_potato', 'id')
    op.alter_column('g07_maize', 'g07_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g07_maize', 'id')
    op.drop_column('g07_fallow', 'id')
    op.alter_column('g07_cotton', 'g07_cotton_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g07_cotton', 'id')
    op.drop_column('g05_soybean', 'id')
    op.alter_column('g05_potato', 'g05_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g05_potato', 'id')
    op.alter_column('g05_maize', 'Date_Time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('g05_maize', 'id')
    op.alter_column('g05_fallow', 'g05_fallow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g05_fallow', 'id')
    op.drop_column('g05_cotton', 'id')
    op.alter_column('g04_soybean', 'g04_soybean_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g04_soybean', 'id')
    op.alter_column('g04_potato', 'g04_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g04_potato', 'id')
    op.alter_column('g04_maize', 'g04_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g04_maize', 'id')
    op.alter_column('g04_cotton', 'g04_cotton_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g04_cotton', 'id')
    op.alter_column('g03_soybean', 'g03_soybean_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g03_soybean', 'id')
    op.add_column('g03_potato', sa.Column('Litter_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Root_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Root_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Humus_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Litter_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Humus_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Manure_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_potato', sa.Column('Manure_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('g03_potato', 'Date_Time',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('g03_potato', 'g03_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g03_potato', 'N2OConc')
    op.drop_column('g03_potato', 'O2Conc')
    op.drop_column('g03_potato', 'CO2Conc')
    op.drop_column('g03_potato', 'Temp')
    op.drop_column('g03_potato', 'NH4N')
    op.drop_column('g03_potato', 'NO3N')
    op.drop_column('g03_potato', 'Q')
    op.drop_column('g03_potato', 'thNew')
    op.drop_column('g03_potato', 'hNew')
    op.drop_column('g03_potato', 'id')
    op.add_column('g03_maize', sa.Column('Litter_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Root_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Root_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Humus_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Litter_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Humus_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Manure_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('g03_maize', sa.Column('Manure_N', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('g03_maize', 'g03_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g03_maize', 'N2OConc')
    op.drop_column('g03_maize', 'O2Conc')
    op.drop_column('g03_maize', 'CO2Conc')
    op.drop_column('g03_maize', 'Temp')
    op.drop_column('g03_maize', 'NH4N')
    op.drop_column('g03_maize', 'NO3N')
    op.drop_column('g03_maize', 'Q')
    op.drop_column('g03_maize', 'thNew')
    op.drop_column('g03_maize', 'hNew')
    op.drop_column('g03_maize', 'id')
    op.drop_column('g03_fallow', 'id')
    op.alter_column('g03_cotton', 'g03_cotton_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g03_cotton', 'id')
    op.alter_column('g01_soybean', 'g01_soybean_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g01_soybean', 'id')
    op.alter_column('g01_potato', 'g01_potato_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g01_potato', 'id')
    op.alter_column('g01_maize', 'g01_maize_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('g01_maize', 'id')
    op.alter_column('g01_cotton', 'Note',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'SRad',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NFruitShed',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NBollsLoss',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NSqLoss',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'NLvsLoss',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_OB',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_GB',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'N_Squares',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Sites',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Nodes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'Date_Time',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('g01_cotton', 'g01_cotton_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('g01_cotton', 'id')
    op.create_table('g01cotton',
    sa.Column('g01_cotton_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date_Time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('PlantH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LAI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LInt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Nodes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Sites', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('N_Squares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('N_GB', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('N_OB', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NLvsLoss', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NSqLoss', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NBollsLoss', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NFruitShed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PetShd_DM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GB_lossDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Lf_lossDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Rt_lossDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Dd_WtDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SquareDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GB_DM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('OB_DM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LeafDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('StemDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RootDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ResC', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PlantDM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('R_S', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('L_Temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Rain', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SRad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PFD', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LeafN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('StemN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SeedN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('BurrN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RootN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Nloss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PlantN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('N_uptake', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('S_Psi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('L_Psi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('LArea', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('VPD', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('StCond', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Pnet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PGross', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('L_Res', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Main_Res', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SPnet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('C_Bal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Nstress_Pn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('g01_cotton_id', name=op.f('g01_cotton_pkey'))
    )
    # ### end Alembic commands ###
