"""make status nullable

Revision ID: 91b0b9683b97
Revises: ff7d635fd790
Create Date: 2026-01-12 00:48:13.043511

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91b0b9683b97'
down_revision = 'ff7d635fd790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pastruns', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pastruns', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
