"""second try to make id autogenerate

Revision ID: a9cfc422cc85
Revises: 68f7836f9a3f
Create Date: 2026-01-16 01:37:04.909531

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a9cfc422cc85'
down_revision = '68f7836f9a3f'
branch_labels = None
depends_on = None


def upgrade():
    pass
"""Make id columns autoincrementing for crop tables

Create Date: 2026-01-15

"""
from alembic import op

# List of all relevant tables
tables = [
    "g01_maize", "g03_maize", "g04_maize", "g05_maize", "g07_maize",
    "g01_soybean", "g03_soybean", "g04_soybean", "g05_soybean", "g07_soybean",
    "g01_cotton", "g03_cotton", "g04_cotton", "g05_cotton", "g07_cotton",
    "g01_potato", "g03_potato", "g04_potato", "g05_potato", "g07_potato",
    "g07_fallow", "g05_fallow", "g03_fallow",
    "plantstress_potato", "nitrogen_potato", "plantStress_maize"
]

def upgrade():
    for table in tables:
        op.execute(f'ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;')

def downgrade():
    for table in tables:
        op.execute(f'ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS;')

def downgrade():
    pass
