"""change ID to int in soilLong

Revision ID: aeffd8727c10
Revises: 76585fc5a140
Create Date: 2026-01-12 19:03:34.043627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aeffd8727c10'
down_revision = '76585fc5a140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soil_long', 'id',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('soil_long_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('soil_long', 'id',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('soil_long_id_seq'::regclass)"))
    # ### end Alembic commands ###
