"""add cotton cultivar table

Revision ID: bcfdbf1e7fea
Revises: c0df8a53e4fb
Create Date: 2026-01-15 02:53:57.072501

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bcfdbf1e7fea'
down_revision = 'c0df8a53e4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultivar_cotton', sa.Column('calbrt1', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt2', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt3', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt4', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt5', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt6', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt7', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt8', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt9', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt10', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt14', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt20', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt21', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt23', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt24', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt25', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt46', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt51', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt53', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt54', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt55', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt56', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt58', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt59', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('calbrt60', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('RRRM', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('RRRY', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('RVRL', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('ALPM', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('ALPY', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('RTWL', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('RTMinWTperArea', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('EPSI', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('IUPW', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('CourMax', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Diffx', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Diffz', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('VelZ', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('lsink', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Rroot', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Constl_M', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('ConstK_M', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Cmin0_M', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('ConstI_Y', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('ConstK_Y', sa.Float(), nullable=True))
    op.add_column('cultivar_cotton', sa.Column('Cmin0_Y', sa.Float(), nullable=True))
    op.alter_column('cultivar_cotton', 'hybridname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cultivar_cotton', 'hybridname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('cultivar_cotton', 'Cmin0_Y')
    op.drop_column('cultivar_cotton', 'ConstK_Y')
    op.drop_column('cultivar_cotton', 'ConstI_Y')
    op.drop_column('cultivar_cotton', 'Cmin0_M')
    op.drop_column('cultivar_cotton', 'ConstK_M')
    op.drop_column('cultivar_cotton', 'Constl_M')
    op.drop_column('cultivar_cotton', 'Rroot')
    op.drop_column('cultivar_cotton', 'lsink')
    op.drop_column('cultivar_cotton', 'VelZ')
    op.drop_column('cultivar_cotton', 'Diffz')
    op.drop_column('cultivar_cotton', 'Diffx')
    op.drop_column('cultivar_cotton', 'CourMax')
    op.drop_column('cultivar_cotton', 'IUPW')
    op.drop_column('cultivar_cotton', 'EPSI')
    op.drop_column('cultivar_cotton', 'RTMinWTperArea')
    op.drop_column('cultivar_cotton', 'RTWL')
    op.drop_column('cultivar_cotton', 'ALPY')
    op.drop_column('cultivar_cotton', 'ALPM')
    op.drop_column('cultivar_cotton', 'RVRL')
    op.drop_column('cultivar_cotton', 'RRRY')
    op.drop_column('cultivar_cotton', 'RRRM')
    op.drop_column('cultivar_cotton', 'calbrt60')
    op.drop_column('cultivar_cotton', 'calbrt59')
    op.drop_column('cultivar_cotton', 'calbrt58')
    op.drop_column('cultivar_cotton', 'calbrt56')
    op.drop_column('cultivar_cotton', 'calbrt55')
    op.drop_column('cultivar_cotton', 'calbrt54')
    op.drop_column('cultivar_cotton', 'calbrt53')
    op.drop_column('cultivar_cotton', 'calbrt51')
    op.drop_column('cultivar_cotton', 'calbrt46')
    op.drop_column('cultivar_cotton', 'calbrt25')
    op.drop_column('cultivar_cotton', 'calbrt24')
    op.drop_column('cultivar_cotton', 'calbrt23')
    op.drop_column('cultivar_cotton', 'calbrt21')
    op.drop_column('cultivar_cotton', 'calbrt20')
    op.drop_column('cultivar_cotton', 'calbrt14')
    op.drop_column('cultivar_cotton', 'calbrt10')
    op.drop_column('cultivar_cotton', 'calbrt9')
    op.drop_column('cultivar_cotton', 'calbrt8')
    op.drop_column('cultivar_cotton', 'calbrt7')
    op.drop_column('cultivar_cotton', 'calbrt6')
    op.drop_column('cultivar_cotton', 'calbrt5')
    op.drop_column('cultivar_cotton', 'calbrt4')
    op.drop_column('cultivar_cotton', 'calbrt3')
    op.drop_column('cultivar_cotton', 'calbrt2')
    op.drop_column('cultivar_cotton', 'calbrt1')
    # ### end Alembic commands ###
