"""add solute table

Revision ID: ccdc3d648964
Revises: f1f8c76fbc4a
Create Date: 2026-01-12 15:06:26.185066

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ccdc3d648964'
down_revision = 'f1f8c76fbc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('EPSI', sa.Float(), nullable=False),
    sa.Column('IUPW', sa.Float(), nullable=False),
    sa.Column('CourMax', sa.Float(), nullable=False),
    sa.Column('Diffusion_Coeff', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solute')
    # ### end Alembic commands ###
