BEGIN TRANSACTION;
DROP TABLE IF EXISTS "cultivar_soybean";
CREATE TABLE IF NOT EXISTS "cultivar_soybean" (
	"id" SERIAL PRIMARY KEY,
	"hybridname"	TEXT,
	"matGrp"	REAL,
	"seedLb"	REAL,
	"fill"	REAL,
	"v1"	REAL,
	"v2"	REAL,
	"v3"	REAL,
	"r1"	REAL,
	"r2"	REAL,
	"r3"	REAL,
	"r4"	REAL,
	"r5"	REAL,
	"r6"	REAL,
	"r7"	REAL,
	"r8"	REAL,
	"r9"	REAL,
	"r10"	REAL,
	"r11"	REAL,
	"r12"	REAL,
	"g1"	REAL,
	"g2"	REAL,
	"g3"	REAL,
	"g4"	REAL,
	"g5"	REAL,
	"g6"	REAL,
	"g7"	REAL,
	"g8"	REAL,
	"g9"	REAL,
	"RRRM"	REAL DEFAULT 166.7,
	"RRRY"	REAL DEFAULT 31.3,
	"RVRL"	REAL DEFAULT 0.73,
	"ALPM"	REAL DEFAULT 0.55,
	"ALPY"	REAL DEFAULT 0.04,
	"RTWL"	REAL DEFAULT 0.000106,
	"RTMinWTperArea"	REAL DEFAULT 0.0002,
	"EPSI"	REAL DEFAULT 1,
	"IUPW"	REAL DEFAULT 1,
	"CourMax"	REAL DEFAULT 1,
	"Diffx"	REAL DEFAULT 2.4,
	"Diffz"	REAL DEFAULT 2.9,
	"VelZ"	REAL DEFAULT 0,
	"lsink"	REAL DEFAULT 1,
	"Rroot"	REAL DEFAULT 0.017,
	"Constl_M"	REAL DEFAULT 35,
	"ConstK_M"	REAL DEFAULT 0.5,
	"Cmin0_M"	REAL DEFAULT 0.01,
	"ConstI_Y"	REAL DEFAULT 17.2,
	"ConstK_Y"	REAL DEFAULT 0.75,
	"Cmin0_Y"	REAL DEFAULT 0.03,
		"owner_id" INTEGER,
	FOREIGN KEY (owner_id) REFERENCES "user"(id) 
);
