"""add default as identity for nitrogen soybean

Revision ID: d2f4fcd71151
Revises: 4f4e6af708a8
Create Date: 2026-01-18 23:42:37.441520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd2f4fcd71151'
down_revision = '4f4e6af708a8'
branch_labels = None
depends_on = None

def upgrade():
   op.execute(f'ALTER TABLE "nitrogen_soybean" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;')  


def downgrade():
   op.execute(f'ALTER TABLE "nitrogen_soybean" ALTER COLUMN id DROP GENERATED BY DEFAULT AS IDENTITY;')  


