"""rename var in cultivar_potato

Revision ID: db42deeabcb1
Revises: fcdc11da6c5c
Create Date: 2026-01-14 03:01:50.426576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db42deeabcb1'
down_revision = 'fcdc11da6c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultivar_potato', sa.Column('Constl_M', sa.Float(), server_default=sa.text('35.0'), nullable=True))
    op.drop_column('cultivar_potato', 'Consl_M')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cultivar_potato', sa.Column('Consl_M', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('35.0'), autoincrement=False, nullable=True))
    op.drop_column('cultivar_potato', 'Constl_M')
    # ### end Alembic commands ###
