"""changed class name for maizdata

Revision ID: e0db066b2de9
Revises: e2bbe2bd4f10
Create Date: 2026-01-12 17:40:04.563477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0db066b2de9'
down_revision = 'e2bbe2bd4f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
