"""add potato cultivar table3

Revision ID: fcdc11da6c5c
Revises: 54f33f0dc8a4
Create Date: 2026-01-14 02:25:19.528749

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcdc11da6c5c'
down_revision = '54f33f0dc8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivar_potato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hybridname', sa.String(), nullable=True),
    sa.Column('A1', sa.Float(), server_default=sa.text('1.5'), nullable=True),
    sa.Column('A6', sa.Float(), server_default=sa.text('2.5'), nullable=True),
    sa.Column('A8', sa.Float(), server_default=sa.text('2.6'), nullable=True),
    sa.Column('A9', sa.Float(), server_default=sa.text('0.8'), nullable=True),
    sa.Column('A10', sa.Float(), server_default=sa.text('1.2'), nullable=True),
    sa.Column('G1', sa.Float(), server_default=sa.text('0.7'), nullable=True),
    sa.Column('G2', sa.Float(), server_default=sa.text('300.0'), nullable=True),
    sa.Column('G3', sa.Float(), server_default=sa.text('15.0'), nullable=True),
    sa.Column('G4', sa.Float(), server_default=sa.text('0.004'), nullable=True),
    sa.Column('RRRM', sa.Float(), server_default=sa.text('166.7'), nullable=True),
    sa.Column('RRRY', sa.Float(), server_default=sa.text('31.3'), nullable=True),
    sa.Column('RVRL', sa.Float(), server_default=sa.text('0.73'), nullable=True),
    sa.Column('ALPM', sa.Float(), server_default=sa.text('0.35'), nullable=True),
    sa.Column('ALPY', sa.Float(), server_default=sa.text('0.04'), nullable=True),
    sa.Column('RTWL', sa.Float(), server_default=sa.text('1.06E-4'), nullable=True),
    sa.Column('RTMinWTperArea', sa.Float(), server_default=sa.text('2.00E-4'), nullable=True),
    sa.Column('EPSI', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('IUPW', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('CourMax', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('Diffx', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('Diffz', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('VelZ', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('lsink', sa.Float(), server_default=sa.text('1'), nullable=True),
    sa.Column('Rroot', sa.Float(), server_default=sa.text('0.017'), nullable=True),
    sa.Column('Consl_M', sa.Float(), server_default=sa.text('35.0'), nullable=True),
    sa.Column('ConstK_M', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('Cmin0_M', sa.Float(), server_default=sa.text('0.01'), nullable=True),
    sa.Column('ConstI_Y', sa.Float(), server_default=sa.text('17.2'), nullable=True),
    sa.Column('ConstK_Y', sa.Float(), server_default=sa.text('0.75'), nullable=True),
    sa.Column('Cmin0_Y', sa.Float(), server_default=sa.text('0.03'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cultivarpotato')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivarpotato',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hybridname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('A1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A6', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A8', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A9', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('A10', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('G1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('G2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('G3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('G4', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('RRRM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RRRY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RVRL', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ALPM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ALPY', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RTWL', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('RTMinWTperArea', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('EPSI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('IUPW', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('CourMax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Diffx', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Diffz', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('VelZ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lsink', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Rroot', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Consl_M', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ConstK_M', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Cmin0_M', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ConstI_Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ConstK_Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Cmin0_Y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('cultivar_potato_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cultivar_potato_pkey'))
    )
    op.drop_table('cultivar_potato')
    # ### end Alembic commands ###
