"""adding_soil_table

Revision ID: fcf2cc8d1ae7
Revises: 7f30e82c38bb
Create Date: 2024-05-20 15:38:32.482082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcf2cc8d1ae7'
down_revision = '7f30e82c38bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil',
    sa.Column("id", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.Column("soilname", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("site_id", sa.Integer(), nullable=False),
    sa.Column("o_gridratio_id", sa.Integer(), nullable=False,  unique=True),
    sa.Column("owner_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.droptable("soil")