BEGIN TRANSACTION;
DROP TABLE IF EXISTS "g01_maize";
CREATE TABLE IF NOT EXISTS "g01_maize" (
	"g01_maize_id"	INTEGER,
	"Date_Time"	TIMESTAMP,
	"jday"	INTEGER,
	"Leaves"	REAL,
	"MaturLvs"	INTEGER,
	"Dropped"	INTEGER,
	"LA_pl"	REAL,
	"LA_dead"	REAL,
	"LAI"	REAL,
	"RH"	REAL,
	"LeafWP"	REAL,
	"PFD"	REAL,
	"SolRad"	REAL,
	"SoilT"	REAL,
	"Tair"	REAL,
	"Tcan"	REAL,
	"ETdmd"	REAL,
	"ETsply"	REAL,
	"Pn"	REAL,
	"Pg"	REAL,
	"Respir"	REAL,
	"av_gs"	REAL,
	"VPD"	REAL,
	"Nitr"	REAL,
	"N_Dem"	REAL,
	"NUpt"	REAL,
	"LeafN"	REAL,
	"PCRL"	REAL,
	"totalDM"	REAL,
	"shootDM"	REAL,
	"earDM"	REAL,
	"TotLeafDM"	REAL,
	"DrpLfDM"	REAL,
	"stemDM"	REAL,
	"rootDM"	REAL,
	"SoilRt"	REAL,
	"MxRtDep"	REAL,
	"AvailW"	REAL,
	"solubleC"	REAL,
	"Note"	TEXT
);
COMMIT;
