BEGIN TRANSACTION;
DROP TABLE IF EXISTS "g01_potato";
CREATE TABLE IF NOT EXISTS "g01_potato" (
	"g01_potato_id"	INTEGER NOT NULL,
	"Date_Time"	TEXT NOT NULL,
	"jday"	INTEGER NOT NULL,
	"LA_pl"	REAL,
	"LAI"	REAL,
	"PFD"	REAL,
	"SolRad"	REAL,
	"Tair"	REAL,
	"Tcan"	REAL,
	"Pgross"	REAL,
	"Rg+Rm"	REAL,
	"Tr-Pot"	REAL,
	"Tr-Act"	REAL,
	"Stage"	REAL,
	"totalDM"	REAL,
	"leafDM"	REAL,
	"stemDM"	REAL,
	"rootDM"	REAL,
	"tuberDM"	REAL,
	"deadDM"	REAL,
	"Cdead"	REAL,
	"Cpool"	REAL,
	"LWPpd"	REAL,
	"LWPave"	REAL,
	"gs_ave"	REAL,
	"Nstress1"	REAL,
	"Nstress2"	REAL,
	"Wstress1"	REAL,
	"Wstress2"	REAL,
	"Wstress3"	REAL
);
COMMIT;
