BEGIN TRANSACTION;
DROP TABLE IF EXISTS "geometry";
CREATE TABLE IF NOT EXISTS "geometry" (
	"simID"	INTEGER,
	"nodeNum"	INTEGER,
	"X"	NUMERIC,
	"Y"	NUMERIC,
	"Layer"	INTEGER,
	"Area"	NUMERIC
);
COMMIT;
